name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install setuptools wheel twine
      - name: run tests
        run: python3 -m unittest -v
